---
title: "Analyses - Community Composition and Structural Equation Modelling"
output: html_document
date: "2026-01-20"
---

# Load Packages
```{r, message=FALSE}
library("tidyverse")
library("lme4")
library("lmerTest")
library("vegan")
```

# Read in the Data
```{r, warning=FALSE}
#Clear environment
rm(list = ls())

setwd("/Users/aska1693/Downloads/Chapter3_DUGresearch/dug-research")

#all site data
sites_all <- read.csv("data/sites_all.csv")

#matrix data for community analyses
inat_wide <- read.csv("data/inat_wide.csv")
arthropods_wide <- read.csv("data/arthropods_wide.csv")
```

# Explore the Data
```{r}

```

GGplot Theme
```{r}
Asia_Theme <- theme(
  plot.title = element_text(size = 16),
  plot.caption = element_text(size = 16),
  axis.title = element_text(size = 20),
  axis.text = element_text(size = 16),
  axis.text.x = element_text(size = 20),
  legend.text = element_text(size= 20))
```

# Community Composition
## Floral NMDS
```{r, echo=FALSE}
set.seed(10)
florNMDS_input <- inat_wide[,-1]
florNMDS_input <- florNMDS_input[rowSums(florNMDS_input > 0) >= 3, ]

flor.mds <- metaMDS(florNMDS_input,k = 3, trymax = 175)
flor.mds
```

## Arthropod Functional Groups
```{r, echo=FALSE}
set.seed(10)
arthropodsNMDS_input <- arthropods_wide[,-1]
arthropods.mds <- metaMDS(arthropodsNMDS_input, trymax = 175)
arthropods.mds

#make nmds into datafram for plotting
arthropods.scores <- as.data.frame(scores(arthropods.mds))
arthropods.scores$site <- rownames(data.scores) 
```

```{r}

```


## Bee Species NMDS
```{r}

```

# Habitat Quality Index
```{r}

```

# Structural Equation Modelling
```{r}

```

