---
title: "Land Cover Data"
author: "Asia Kaiser"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r}
library(terra)
library(sf)
library(sp)
library(tidyverse)
```


## Read in the Data
```{r}
setwd("/Users/aska1693/Downloads/Chapter3_DUGresearch/dug-research")
sites <- read.csv("data/site_data.csv")

imperv_path <- "data/NLCD_mf5qnksxr8tzfi/Annual_NLCD_FctImp_2024_CU_C1V1_mf5qnksxr8tzfi.tiff"
tcc_path <- "data/NLCD_mf5qnksxr8tzfi/nlcd_tcc_conus_wgs84_v2023-5_20230101_20231231_mf5qnksxr8tzfi.tiff"

# Load rasters into R
tcc_ras <- rast(tcc_path)  # Tree canopy cover raster
imperv_ras <- rast(imperv_path)
```

# Extract Raster Data

Extract City Coordinates
```{r}
# Extract city coordinates
garden_coords <- st_as_sf(sites, coords = c("Long", "Lat"), crs = 4326) # Use EPSG 4326 for WGS84
```

Extract Raster CRS
```{r}
# Get the CRS of the rasters (assuming both rasters have the same CRS)
crs_rasters <- crs(tcc_ras)
```

Extract mean raster values within each buffer
```{r}
# Create a buffer around sites
buffer_radius <- c(200, 500, 1000)  # set to desired buffer size (in meters)

# Function to extract summed raster values for buffers
extract_raster_mean <- function(raster, buffers) {
  extracted_values <- terra::extract(raster, as(buffers, "SpatVector"), fun = mean, na.rm = TRUE)
  extracted_values[, 2]  # summed values in second column
}

for (i in buffer_radius) {
  # create buffer of radius i
  garden_buffer <- st_transform(
    st_buffer(st_transform(garden_coords, crs_rasters), dist = i),
    crs_rasters
  )
  
  # dynamic column names
  tcc_col <- paste0("tcc", i, "m")
  imp_col <- paste0("imp", i, "m")
  
  # extract and save into dataframe
  sites[[tcc_col]] <- extract_raster_mean(tcc_ras, garden_buffer)
  sites[[imp_col]] <- extract_raster_mean(imperv_ras, garden_buffer)
}
```

Final dataframe
```{r}
# View the final dataframe
print(sites)
```

### Project cities points onto rasters
```{r}
plot(tcc_ras,
     main = "Tree Canopy Cover")
plot(garden_coords$geometry,
     pch = 19)
```

```{r}
plot(imperv_ras,
     main = "Impervious Surface")
plot(garden_coords$geometry)
```

Save updated sites dataframe as csv
```{r}
write.csv(sites, "/Users/aska1693/Downloads/Chapter3_DUGresearch/dug-research/data/DUG_sites.csv", row.names = FALSE)
```

