---
title: "Data Cleaning"
output: html_document
date: "2025-08-29"
---

# Load Packages
```{r}
library("tidyverse")
library("lme4")
library("lmerTest")
```
# Read in the Data
```{r}
#Clear environment
rm(list = ls())

#Load in all datasets
setwd("/Users/aska1693/Downloads/Chapter3_DUGresearch/dug-research")
arthropods_jun_raw <- read.csv("data/arthropod_data_june.csv", na.strings = c("", " "))
cucumbers_raw <- read.csv("data/cucumber_data.csv", na.strings = c("", " "))
sites_raw <- read.csv("data/DUG_sites.csv", na.strings = c("", " "))
```

# Explore the data
```{r}
str(arthropods_jun_raw)
str(cucumbers_raw)
str(sites_raw)
```
# Data Cleaning 

Select subset of site variables
```{r}
#Select which site level variables you want to keep in dataframe
sites <- sites_raw %>%
    select(Site, site_code, Area_m2, Plots, WealthIndex, tcc200m, imp200m, tcc500m, imp500m)
str(sites)
```

Descriptive statistics of site level variables
```{r}
site_statistics <- sites %>%
  summarise(across(c(Area_m2, Plots, WealthIndex, tcc200m, imp200m),
                   list(mean = ~mean(.x, na.rm = TRUE),
                        sd   = ~sd(.x, na.rm = TRUE)),
                   .names = "{.fn}_{.col}"))%>%
    pivot_longer(everything(),
               names_to = c("stat", "variable"),
               names_sep = "_") %>%
    pivot_wider(names_from = variable, values_from = value)
site_statistics 
```

## Cucumber data
```{r}
#Average cucumber values by treatment by site
cucumbers_avg <- cucumbers_raw %>%
    mutate(seed_mass_ratio = no_seeds/mass_g)%>%
    group_by(site_code, treatment) %>%
    summarise(
        avg_mass = mean(mass_g, na.rm = TRUE),
        avg_seeds = mean(no_seeds, na.rm = TRUE),
        avg_length = mean(length_mm, na.rm = TRUE),
        avg_width = mean(width, na.rm = TRUE),
        avg_volume = mean(volume_mL, na.rm = TRUE),
        prop_cylindrical = mean(cylindrical == "Yes", na.rm = TRUE),
        avg_seed_mass_ratio = mean(seed_mass_ratio, na.rm = TRUE))
    
cucumbers_avg
 
#Difference (Pollinated - Control) for cucumber values by site
cucumbers_delta <-  cucumbers_avg %>%
   arrange(site_code, treatment) %>% 
    group_by(site_code) %>%
  summarise(
    delta_mass  = diff(avg_mass),
    delta_seeds = diff(avg_seeds),
    delta_length = diff(avg_length),
    delta_width = diff(avg_width),
    delta_volume = diff(avg_volume),
    delta_cylindrical = diff(prop_cylindrical),
    delta_seed_mass_ratio = diff(avg_seed_mass_ratio))
cucumbers_delta

```

## Arthropod Data (June Preliminary Data)
### Functional Groups
```{r}
#Functional groups across sites
arthropods <- arthropods_jun_raw %>%
    group_by(fun_group, site_code)%>%
    summarise(n.obs = n())

    #mutate(fun_group = replace_na(fun_group, "Unknown"))
arthropods 
```
```{r}
#Plot of functional groups
fun_plot <- ggplot(data = arthropods, aes(x = reorder(fun_group, n.obs), y = n.obs))+
    geom_bar(stat = "identity")+
     coord_flip()+
    theme_classic()+
    labs(x = "",
         y = "Number of arthropods collected",
         title = "Arthropod Functional Groups",
         caption = "\n The number of arthropods (insects and arachnids) we collected in each functional \n group in vane and pitfall traps across 21 garden sites in June 2025.")
fun_plot
```
### Common Taxa
```{r}
arthropods_taxa_fam <- arthropods_jun_raw %>%
    group_by(fam)%>%
    summarise(n.obs = n())
arthropods_taxa_fam

arthropods_taxa_order <- arthropods_jun_raw %>%
    group_by(order)%>%
    summarise(n.obs = n())%>%
    filter(n.obs > 100)
arthropods_taxa_order
```

```{r}
taxa_plot <- ggplot(data = arthropods_taxa_order, aes(x = reorder(order, n.obs), y = n.obs))+
    geom_bar(stat = "identity", width = 0.5)+
     coord_flip()+
    theme_classic()+
    labs(x = "",
         y = "",
         title = "Most Common Taxa")+
    theme(plot.title = element_text(size = 20),
          axis.text.x = element_text(size = 20),
          axis.text.y = element_text(size = 20))
taxa_plot

ggsave("/Users/aska1693/Downloads/Chapter3_DUGresearch/dug-research/figures/June_TopTaxa_plot.png", taxa_plot, width = 6, height = 10, units = "in")
```



